### ISSUE TITLE
Lumen 5.5 incompatible 

### ISSUE THREAD

**Issue by chriscalip** [thedevsaddam/lumen-route-list#1]
Steps to recreate : 
Simply install on lumen 5.5
Install this package.
Use `php artisan route:list`

Screenshot attached.
![lumen-route-list-error](https://user-images.githubusercontent.com/479454/30676176-5bfa4aba-9e4a-11e7-8736-d5a6a6d0bead.png)

**Comment by chriscalip** [comment]
https://gist.github.com/chriscalip/b4c59cc4a45797c0cc77d4a47012a8a3

Looks like lumen 5.5 & lumen 5.4 deprecated $app->getRoutes() utility. 

Heads up, I'll stop participating on this issue for the time being because : I switched back to laravel 5.5 for api microservice and I wont dealing with lumen issues for the time being.

**Comment by thedevsaddam** [comment]
@chriscalip 👍  I have fixed the issue.
