### ISSUE TITLE
Lumen 5.5 - No routes found

### ISSUE THREAD

**Issue by bradiosd** [thedevsaddam/lumen-route-list#2]
Running the following command returns "No routes found!" (see screenshot).

`php artisan route:list`

![image](https://user-images.githubusercontent.com/2276905/36143140-23477d62-10a2-11e8-8b80-8d183dff81a6.png)

**Comment by thedevsaddam** [comment]
@bb128b Please use this [package](https://github.com/appzcoder/lumen-route-list), hope this will work :)

**Comment by SomePlayer** [comment]
It works in Lumen 8,
just remember to  add

`$app->register(\Thedevsaddam\LumenRouteList\LumenRouteListServiceProvider::class);` to bootstrap/app.php 

I was following a guide, and it did not mention the step.

Also if using routes/api.php add it to the bootstrap/app.php as well

`$app->router->group([
    'namespace' => 'App\Http\Controllers',
], function ($router) {
    require __DIR__.'/../routes/web.php';
    require __DIR__.'/../routes/api.php';
});`
